class Autogenerated {
  List<Users>? users;
  List<Post>? post;
  List<Comment>? comment;

  Autogenerated({this.users, this.post, this.comment});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['users'] != null) {
      users = <Users>[];
      json['users'].forEach((v) {
        users!.add(new Users.fromJson(v));
      });
    }
    if (json['post'] != null) {
      post = <Post>[];
      json['post'].forEach((v) {
        post!.add(new Post.fromJson(v));
      });
    }
    if (json['comment'] != null) {
      comment = <Comment>[];
      json['comment'].forEach((v) {
        comment!.add(new Comment.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.users != null) {
      data['users'] = this.users!.map((v) => v.toJson()).toList();
    }
    if (this.post != null) {
      data['post'] = this.post!.map((v) => v.toJson()).toList();
    }
    if (this.comment != null) {
      data['comment'] = this.comment!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Users {
  String? username;
  String? password;
  String? address;
  String? phoneNumber;
  int? id;

  Users(
      {this.username, this.password, this.address, this.phoneNumber, this.id});

  Users.fromJson(Map<String, dynamic> json) {
    username = json['username'];
    password = json['password'];
    address = json['address'];
    phoneNumber = json['phoneNumber'];
    id = json['id'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['username'] = this.username;
    data['password'] = this.password;
    data['address'] = this.address;
    data['phoneNumber'] = this.phoneNumber;
    data['id'] = this.id;
    return data;
  }
}

class Post {
  String? username;
  String? textpost;
  String? imgPath;
  int? id;
  List<String>? likedUsers;

  Post({this.username, this.textpost, this.imgPath, this.id, this.likedUsers});

  Post.fromJson(Map<String, dynamic> json) {
    username = json['username'];
    textpost = json['textpost'];
    imgPath = json['img_path'];
    id = json['id'];
    likedUsers = json['likedUsers'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['username'] = this.username;
    data['textpost'] = this.textpost;
    data['img_path'] = this.imgPath;
    data['id'] = this.id;
    data['likedUsers'] = this.likedUsers;
    return data;
  }
}

class Comment {
  int? postid;
  List<CommentAll>? commentAll;
  int? id;

  Comment({this.postid, this.commentAll, this.id});

  Comment.fromJson(Map<String, dynamic> json) {
    postid = json['postid'];
    if (json['comment_all'] != null) {
      commentAll = <CommentAll>[];
      json['comment_all'].forEach((v) {
        commentAll!.add(new CommentAll.fromJson(v));
      });
    }
    id = json['id'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['postid'] = this.postid;
    if (this.commentAll != null) {
      data['comment_all'] = this.commentAll!.map((v) => v.toJson()).toList();
    }
    data['id'] = this.id;
    return data;
  }
}

class Notificationaa {
  int? id;
  int? postId; // รหัสโพสที่เกี่ยวข้อง
  String? username; // ชื่อผู้ใช้ที่แจ้งเตือน
  String? type; // ประเภทการแจ้งเตือน (ไลค์หรือความคิดเห็น)
  String? des; // เพิ่มฟิลด์ "des"
  String? time;
  String? actionUsername; // เพิ่มฟิลด์ "actionUsername"

  Notificationaa({
    this.id,
    this.postId,
    this.username,
    this.type,
    this.des,
    this.time,
    this.actionUsername,
  });

  Notificationaa.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    postId = json['post_id'];
    username = json['username'];
    type = json['type'];
    des = json['des']; // อ่านข้อมูลจากฟิลด์ "des"
    time = json['time'];
    actionUsername = json['actionUsername']; // อ่านข้อมูลจากฟิลด์ "actionUsername"
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['post_id'] = this.postId;
    data['username'] = this.username;
    data['type'] = this.type;
    data['des'] = this.des; // เพิ่มฟิลด์ "des"
    data['time'] = this.time;
    data['actionUsername'] = this.actionUsername; // เพิ่มฟิลด์ "actionUsername"
    return data;
  }
}





class CommentAll {
  String? username;
  String? textComment;

  CommentAll({this.username, this.textComment});

  CommentAll.fromJson(Map<String, dynamic> json) {
    username = json['username'];
    textComment = json['text_comment'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['username'] = this.username;
    data['text_comment'] = this.textComment;
    return data;
  }
}
